// Code generated by protoc-gen-go. DO NOT EDIT.
// source: point/point.proto

package point

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Point struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_67cd87673a1f2589, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type PointResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointResponse) Reset()         { *m = PointResponse{} }
func (m *PointResponse) String() string { return proto.CompactTextString(m) }
func (*PointResponse) ProtoMessage()    {}
func (*PointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67cd87673a1f2589, []int{1}
}

func (m *PointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointResponse.Unmarshal(m, b)
}
func (m *PointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointResponse.Marshal(b, m, deterministic)
}
func (m *PointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointResponse.Merge(m, src)
}
func (m *PointResponse) XXX_Size() int {
	return xxx_messageInfo_PointResponse.Size(m)
}
func (m *PointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PointResponse proto.InternalMessageInfo

func (m *PointResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PointResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "point.Point")
	proto.RegisterType((*PointResponse)(nil), "point.PointResponse")
}

func init() { proto.RegisterFile("point/point.proto", fileDescriptor_67cd87673a1f2589) }

var fileDescriptor_67cd87673a1f2589 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xc8, 0xcf, 0xcc,
	0x2b, 0xd1, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x92, 0x32,
	0x17, 0x6b, 0x00, 0x88, 0x21, 0xc4, 0xc3, 0xc5, 0x58, 0x21, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a,
	0xc4, 0x58, 0x01, 0xe2, 0x55, 0x4a, 0x30, 0x41, 0x78, 0x95, 0x4a, 0xb6, 0x5c, 0xbc, 0x60, 0x45,
	0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5,
	0x89, 0xe9, 0xa9, 0x60, 0x2d, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x10, 0x17, 0x4b, 0x72, 0x7e, 0x4a,
	0x2a, 0x54, 0x2f, 0x98, 0x6d, 0x64, 0xcf, 0xc5, 0x15, 0x94, 0x5f, 0x5a, 0x92, 0xea, 0x5e, 0x9a,
	0x99, 0x92, 0x2a, 0x64, 0xc8, 0xc5, 0xed, 0x9e, 0x5a, 0xe2, 0x93, 0x9f, 0x9c, 0x58, 0x92, 0x99,
	0x9f, 0x27, 0xc4, 0xa3, 0x07, 0x71, 0x15, 0xd8, 0x02, 0x29, 0x11, 0x64, 0x1e, 0xcc, 0xba, 0x24,
	0x36, 0xb0, 0x93, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x08, 0x0f, 0x62, 0xc7, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouteGuideClient is the client API for RouteGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteGuideClient interface {
	GetLocation(ctx context.Context, in *Point, opts ...grpc.CallOption) (*PointResponse, error)
}

type routeGuideClient struct {
	cc *grpc.ClientConn
}

func NewRouteGuideClient(cc *grpc.ClientConn) RouteGuideClient {
	return &routeGuideClient{cc}
}

func (c *routeGuideClient) GetLocation(ctx context.Context, in *Point, opts ...grpc.CallOption) (*PointResponse, error) {
	out := new(PointResponse)
	err := c.cc.Invoke(ctx, "/point.RouteGuide/GetLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteGuideServer is the server API for RouteGuide service.
type RouteGuideServer interface {
	GetLocation(context.Context, *Point) (*PointResponse, error)
}

// UnimplementedRouteGuideServer can be embedded to have forward compatible implementations.
type UnimplementedRouteGuideServer struct {
}

func (*UnimplementedRouteGuideServer) GetLocation(ctx context.Context, req *Point) (*PointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocation not implemented")
}

func RegisterRouteGuideServer(s *grpc.Server, srv RouteGuideServer) {
	s.RegisterService(&_RouteGuide_serviceDesc, srv)
}

func _RouteGuide_GetLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).GetLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/point.RouteGuide/GetLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).GetLocation(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouteGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "point.RouteGuide",
	HandlerType: (*RouteGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLocation",
			Handler:    _RouteGuide_GetLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "point/point.proto",
}
